artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL:  https://github.com/ISHAWANT/Data_set/raw/main/cat-dog-data.zip 
  # source_URL: C:\Users\ishawant\PycharmProjects\CNNClassifier\cat-dog-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
